version: '3.8'

services:
  app:

    image: kjk1023/finto:latest
    container_name: spring-app-container
    ports:

      - "8080:8080"
    depends_on:
      - db
    environment:

      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/finto
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db-container
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=finto
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: